language: node_js
node_js:
  - 16 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "adminpage";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm run build:prod # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.9.3
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: carrectly-admin-staging
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: bv0dJxYI5Vcj0W7oSIZCSmHhvalYabjFgWiU9bEHYURyifg2Qm1luVSqaPjeKDxrgSewtpSqvF8iBtN2RQ5w90DE+8NqPr0lCf6fqYBT3xxPi1bGTfsKP9TqL54TxvSOJV2ImOc3y5YCEeGVd0w4Ct80RknNARrBMlFRvCXdQ3Tt2qwJadfbGBLgytc965eaIfxpR57JAoorjkYDeEdvIBlG1dFVmX38IsVz+KreRa9LAmmgGwx347T3rltOhIFMB45zvlN6ubojudqZ087uUxT/zSdDpOlcbxxoLURbpHbxjmWfyQig6kQZ/7T1UB8wfwjI1Ri1UqhukUX6Jm7lyXzqw96RfV2kzwmNee7mFk9TbIyWW4nZoRio6kkkrJB3bxyiFWViTnLfF7QDEAXxk3GJ8Vp5UGZ4DK8T9EPwofRMfiSmqvhxwWon4ofPY5d+P23mvAULS86vOoMgrID31DyrMUJnHNATDrhr8aYHZPfMJ9YxcTDXbQzErj+fyB9GC1I77PG5ZeMd3wiEHNRxyGsFtEYT6WeKWzHZ59/sLD/HO4EkGGSsScHyMME0T7gV8HNV/Ik3yvBVSOKOHStvzqE34Bc5VngHZJ1QX5CmjZvoeeiK/+w1B/Rkt3XmNfDc8ILcBD5SvpP3eG4QdL5rUCof9uIviZ3Huw5/c8l/OdE=
