language: node_js
node_js:
  - 16 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "adminpage";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm run build:prod # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.9.3
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: carrectly-admin-staging
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: BHlQySYbEmE1igcQzYxDKJChklH7SW4eHI7o/JfozcOVz7YuNLrKdP0aYNZHBl21lnqBmvSWHNYYFbhMMtJ2dZNj81KAvHSj9VD9oBSU4SN0YRXCKep4VpgJk/p0t9W0bucnUe2Z5oRt8Q+RfW8Nv5IGPM6+5rwmz6QbEgd9cS9srBEL1WXkF3OonuVZp0ROmQMbvZOcvZ1VAeK0K3K38ZSsttBirs1PaL3sxeAW0Q+UdeJYLtaaVxWGspf0eEeyBP/JJ9Z/fqTvDhpZdwcXMEsskPfx0h2BWS/XQMPM6C8qu9X5GglZow4RiHsyHn+NZs86IP5R4bfvueJf6rUJHyW/wflPsP74C3jwM180iyFtZpzfZ9VXyj8Hd4M2m7xBXxy8FuAIbLLNhbc2EmlkyRFKV5835ZFDH2WUeD4kgGGcz4tqMsY97LZocffUwK0SVaQvxW/uITCGKvtxmjPc5Ax7VEuzCN+W/aa7MfZMVMUHpcr094XSaZM4pRsc1sWg+TVg/4gi+R4QUk6LnsOrAx8wNSYiT9TG3+ZWdRY2VeZAMr0vrFxj4EhL7HdNESD5leSPg7X8bmmQr2Dfktl8Fq41ZK0/q/z4KUJfRtfic/nuRBrGr4MZ9+93otRqLwKdWs3JO31t0f6zhgKFQur8joQVc3weXrfyBRQbCDYhbFA=
